syntax = "proto3";

package apply;

option go_package = "kama_chat_server/api/gen/apply";

service ApplyService {
    rpc ApplyFriend (ApplyFriendRequest) returns (ApplyFriendResponse);
    rpc ApplyGroup (ApplyGroupRequest) returns (ApplyGroupResponse);
    rpc GetFriendApplyList (GetFriendApplyListRequest) returns (GetFriendApplyListResponse);
    rpc GetGroupApplyList (GetGroupApplyListRequest) returns (GetGroupApplyListResponse);
    rpc PassFriendApply (PassFriendApplyRequest) returns (PassFriendApplyResponse);
    rpc PassGroupApply (PassGroupApplyRequest) returns (PassGroupApplyResponse);
    rpc RefuseFriendApply (RefuseFriendApplyRequest) returns (RefuseFriendApplyResponse);
    rpc RefuseGroupApply (RefuseGroupApplyRequest) returns (RefuseGroupApplyResponse);
    rpc BlackFriendApply (BlackFriendApplyRequest) returns (BlackFriendApplyResponse);
    rpc BlackGroupApply (BlackGroupApplyRequest) returns (BlackGroupApplyResponse);
}

message ApplyFriendRequest {
    string user_id = 1;
    string friend_id = 2;
    string message = 3;
}
message ApplyFriendResponse {}

message ApplyGroupRequest {
    string user_id = 1;
    string group_id = 2;
    string message = 3;
}
message ApplyGroupResponse {}

message GetFriendApplyListRequest {
    string user_id = 1;
    int32 page = 2;
    int32 page_size = 3;
}
message FriendApplyListRespond {
    string applicant_id = 1;
    string applicant_name = 2;
    string applicant_avatar = 3;
    string message = 4;
}
message GetFriendApplyListResponse {
    int64 total = 1;
    repeated FriendApplyListRespond list = 2;
}

message GetGroupApplyListRequest {
    string operator_id = 1;
    string group_id = 2;
    int32 page = 3;
    int32 page_size = 4;
}
message GroupApplyListRespond {
    string applicant_id = 1;
    string applicant_name = 2;
    string applicant_avatar = 3;
    string message = 4;
}
message GetGroupApplyListResponse {
    int64 total = 1;
    repeated GroupApplyListRespond list = 2;
}

message PassFriendApplyRequest {
    string user_id = 1;
    string applicant_id = 2;
}
message PassFriendApplyResponse {}

message PassGroupApplyRequest {
    string operator_id = 1;
    string group_id = 2;
    string applicant_id = 3;
}
message PassGroupApplyResponse {}

message RefuseFriendApplyRequest {
    string user_id = 1;
    string applicant_id = 2;
}
message RefuseFriendApplyResponse {}

message RefuseGroupApplyRequest {
    string operator_id = 1;
    string group_id = 2;
    string applicant_id = 3;
}
message RefuseGroupApplyResponse {}

message BlackFriendApplyRequest {
    string user_id = 1;
    string applicant_id = 2;
}
message BlackFriendApplyResponse {}

message BlackGroupApplyRequest {
    string operator_id = 1;
    string group_id = 2;
    string applicant_id = 3;
}
message BlackGroupApplyResponse {}
