apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: chat-system
spec:
  serviceName: "etcd"
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.5
          ports:
            - containerPort: 2379
            - containerPort: 2380
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://0.0.0.0:2379"
          volumeMounts:
            - name: etcd-data
              mountPath: /bitnami/etcd/data
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: chat-system
spec:
  ports:
    - name: client
      port: 2379
    - name: peer
      port: 2380
  selector:
    app: etcd
